### ISSUE TITLE
Download does not reach the end

### ISSUE THREAD

**Issue by PedroAQCoutinho** [yannforget/landsatxplore#1]
Hello Yann,

Thanks so much for this module; helped me so much. Here's the thing: I'm running the code for download landsat_8 images, simple as you described in the description for usage; but my downloads don't finish... They stop in 96%, do you know why this is happening ?

**Comment by yannforget** [comment]
Hello,

If the file size cannot be retrieved from the HTTP headers, the progress bar uses an estimation based on the dataset ; so your image could have been fully downloaded. Did you check ?

Working on a way to improve this,

Yann

**Comment by PedroAQCoutinho** [comment]
Ahh, you solved my problem... It is dowloading the full file, but is only showing until 96% in the prompt !!!

Thanks man, so much

**Comment by sjdqbyitr178crs813tgbr8gsdufygeuy53** [comment]
That [pull request](https://github.com/yannforget/landsatxplore/pull/7) fix the problem.
