### ISSUE TITLE
bbox with api

### ISSUE THREAD

**Issue by pbugnet** [yannforget/landsatxplore#10]
Hi. I'm trying to use your api with a bbox parameter instead of longitude and latitude but i keep getting an empty list. Am i missing something?

**Comment by yannforget** [comment]
Hi,

What code did you use ?

Bounding box must be provided in the following format: (min lat, min lon, max lat, max lon)

**Comment by pbugnet** [comment]
Thanks Yann, it works just fine in this order. I'm using the landsatxplore api.
Pierre
