### ISSUE TITLE
KeyError: 'content-disposition'

### ISSUE THREAD

**Issue by baptistebordet1** [yannforget/landsatxplore#105]
Hello, 

I haven't used the package for more than a year and now I got an issue while trying to download data from Landsat 8 Collection 2 with the API search. 

I have the following error : 

```
  File "C:\Users\borde\anaconda3\lib\site-packages\landsatxplore\earthexplorer.py", line 90, in _download
    local_filename, filesize = self._get_fileinfo(

  File "C:\Users\borde\anaconda3\lib\site-packages\landsatxplore\earthexplorer.py", line 145, in _get_fileinfo
    local_filename = r.headers["Content-Disposition"].split("=")[-1]

  File "C:\Users\borde\anaconda3\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]

KeyError: 'content-disposition'
```

After diging a little bit I found out that in the self._get_fileinfo function the Header dosen't have a "Content-disposition" (only tested for Landsat 8 COllection 2 lvl 1 and lvl 2). 

Does anyone have experienced the same Issue ? @valpamp Maybe you haev some ideas on this ?

**Comment by WortalMombat** [comment]
I have the same issue. Before the error from above is thrown, I also get a `landsatxplore.errors.EarthExplorerError: Download is not available`.

I've been looking into it but found no solution so far.

**Comment by baptistebordet1** [comment]
@WortalMombat Your error appears because the dataset is not the right one. You can try to add the dataset name in the EarthExplorer.download() if it's not the case now. 

Regarding my issue content disposition is back in r.headers[]. I still don't know why it happened
