### ISSUE TITLE
it seems that the function 'Earth_Down = EarthExplorer(username, password)' does not work

### ISSUE THREAD

**Issue by ChangpeiHe** [yannforget/landsatxplore#109]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='m2m.cr.usgs.gov', port=443): Max retries exceeded with url: /api/api/json/stable/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fea140bf710>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by ChangpeiHe** [comment]
![image](https://github.com/yannforget/landsatxplore/assets/126058879/2011be3d-6a04-41e0-9a8d-2a2c78214e3d)

**Comment by ChangpeiHe** [comment]
adding  ‘verify=False’ to session.get()  can solve this problem

**Comment by neteler** [comment]
Would you mind to open a pull request for the change? Then it will be easier to test it.
