### ISSUE TITLE
using bbox

### ISSUE THREAD

**Issue by ben-davison** [yannforget/landsatxplore#13]
Hi, I would like to download all Landsat 8 scenes that intersect a bounding box. Is this provided by the bbox option? If so, can you explain the syntax as I cannot get it to work.

I've tried: landsatxplore search --dataset LANDSAT_8_C1 --bbox -49.73 64.2 -49.48 64.3 --start 2018-03-01 --end 2018-09-01 --output csv > results.csv
which returns no results.

However: landsatxplore search --dataset LANDSAT_8_C1 --location 64.2 -49.73 --start 2018-03-01 --end 2018-09-01 --output csv > results.csv
returns many results

Thanks,

Ben

**Comment by yannforget** [comment]
Hi,
what about `--bbox 64.2 -49.73 64.3 -49.48` ?
