### ISSUE TITLE
EE: Could not find api key 

### ISSUE THREAD

**Issue by eamanu** [yannforget/landsatxplore#14]
Hi!

When I try to download a set of scenes, I have this error:

```
py3.6.egg/landsatxplore/api.py", line 41, in request raise EarthExplorerError('EE: {}'.format(response['error'])) landsatxplore.exceptions.EarthExplorerError: EE: Could not find api key
```
landsatxplore download the first image but, the other fail with that error.

I am trying to download:

`LC08_L1TP_220078_20181211_20181226_01_T1` and `LC08_L1TP_220078_20190128_20190206_01_T1`

**Comment by yannforget** [comment]
Hi and thanks for the bug report,

How did you set your credentials before running the command ? Are you sure they were valid ?

You can try with [`pylandsat`](https://github.com/yannforget/pylandsat) which uses Google Public Cloud instead of the USGS servers and doesn't require any credential.

**Comment by eamanu** [comment]
Hi @yannforget thanks for the report.

I was using the credentials normally, I was downloading severals images, but one thay I had that problems.

I sincerely suspect on EE have some "protecting mechanism" to avoid lot of bots using the service. But I need a expert opinion. I have not experience using EE.

THanks for tip of use pylandsat. I will test it.

**Comment by yannforget** [comment]
Yes, IIRC there is a limit of 3 concurrent connections per account or IP address. Sometimes the request just fails and I didn't implement any retry procedure. That's why I coded `pylandsat` as a replacement

**Comment by eamanu** [comment]
Thanks @yannforget the last comments explain the problem that I have, so I think this is not a landsatxplore's issue. So, I wil take the recommendation to use pylandsat. 

Thanks, close the issue. :)
