### ISSUE TITLE
Problem with Scene Search and EE downloads

### ISSUE THREAD

**Issue by romens96** [yannforget/landsatxplore#16]
Hi @yannforget , I've encounter these issue very recently. I have included the error below. Any chance its due to the USGS upgraded?
The error for scene search:

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The error for EE logins:

EarthExplorerError: EE: login failed (csrf token not found).

**Comment by DancingChild** [comment]
I also encountered the same problem, but it can still be used normally before June 17, but this problem occurred after an upgrade of USGS. In addition, my USGS account cannot be logged in. Will it be blocked?

**Comment by UTW-Agro** [comment]
I am also having the same problem. Before the update it worked perfectly and now it gives me the same error

**Comment by yannforget** [comment]
Hi and thanks for the bug reports!

Yes, a lot of things changed. I fixed the login issue in the last commit. I'm waiting to fix scene downloading before pushing a new release, but for now I cannot even download scenes from the web interface.

**Comment by romens96** [comment]
@yannforget Thank you so much for the quick updates! Really appreciate it!
 
I have the same issue here when i try to download from the web interface.

I found that the download directory have change when I was trying to see whats the problem.
Instead of the previous one:
EE_DOWNLOAD_URL = 'https://earthexplorer.usgs.gov/download/{folder}/{sid}/STANDARD/EE'

Now i think it has change to the format below:
'https://earthexplorer.usgs.gov/download/external/options/{folder}/{sid}/M2M/

Hope this info helps.
Thanks again!

**Comment by yannforget** [comment]
Thanks! This helps. Also I just saw that they upgraded their API to [v1.5](https://m2m.cr.usgs.gov/) and that the old one will be deprecated, so the API module have to be updated.

**Comment by romens96** [comment]
Hi @yannforget Thanks for your help in this issue!

Currently it works like a charm. Closing this issue :)
