### ISSUE TITLE
Band LandSat 8

### ISSUE THREAD

**Issue by renandantas** [yannforget/landsatxplore#2]
You know if it's possible to change the band quantity that will be downloaded? Because in my case i just need the pure image, without any filter. You have any suggestion in this case?

**Comment by yannforget** [comment]
Hello,
Earth Explorer only allows the download of a `zip` archive with all the bands included.
I think it is possible to download individual bands using the public dataset hosted on Google:
https://cloud.google.com/storage/docs/public-datasets/landsat
Download speeds are also a lot better...

**Comment by renandantas** [comment]
Ok, i will try this. Thanks
