### ISSUE TITLE
scenes retrieved do not correspond to bbox provided

### ISSUE THREAD

**Issue by veroandreo** [yannforget/landsatxplore#23]
Hello,

I'm trying to write a wrapper for GRASS GIS using landsatxplore. See [i.landsat.download](https://github.com/veroandreo/i.landsat/blob/main/i.landsat.download/i.landsat.download.py). It is really basic right now.

However in my tests using landsatxplore api and passing a bbox like a tuple obtained either from the extent of a vector map or the region settings in GRASS GIS: `('-78.77428134', '35.68792712', '-78.60830318', '35.80960938')`, I get scenes located in Antarctica (while the coordinates belong to an area in North Carolina state). This is the script I use just to test:

```
#!/usr/bin/env python

import landsatxplore.api

# Initialize a new API instance and get an access key
api = landsatxplore.api.API('user', 'password')

# Request
scenes = api.search(
    dataset='LANDSAT_ETM_C1',
    bbox = ('-78.77428134', '35.68792712', '-78.60830318', '35.80960938'), #(xmin, ymin, xmax, ymax)
    start_date='2000-01-01',
    end_date='2000-07-01',
    max_cloud_cover=10)

print('{} scenes found.'.format(len(scenes)))

print('ID', 'DisplayID', 'Date', 'Clouds')
for scene in scenes:
    print(scene['entityId'], scene['displayId'], scene['acquisitionDate'], scene['cloudCover'])

api.logout()
```

The bbox corresponds to a small area in North Carolina state, however, I get scenes with path and row from Antartica
```
5 scenes found.
ID DisplayID Date Clouds
LE71311172000001EDC00 LE07_L1GT_131117_20000101_20170215_01_T2 2000-01-01 0.00
LE71381162000002SGS00 LE07_L1GT_138116_20000102_20170215_01_T2 2000-01-02 0.00
LE71361162000004SGS00 LE07_L1GT_136116_20000104_20170215_01_T2 2000-01-04 0.00
LE71361172000004SGS00 LE07_L1GT_136117_20000104_20170215_01_T2 2000-01-04 0.00
LE71331172000015SGS01 LE07_L1GT_133117_20000115_20170215_01_T2 2000-01-15 0.00
```

Is there a problem with the bbox I'm passing or is it in the api? 
When I use the options `longitude` and `latitude` instead of `bbox`, I get the right path and rows: 

```
# all the rest the same
scenes = api.search(
    dataset='LANDSAT_ETM_C1',
    longitude=-78.77428134,
    latitude=35.68792712,
    start_date='2000-01-01',
    end_date='2000-07-01',
    max_cloud_cover=10)

# result
10 scenes found.
ID DisplayID Date Clouds
LE70160352000011EDC00 LE07_L1TP_016035_20000111_20161002_01_T1 2000-01-11 0.00
LE70160352000027EDC00 LE07_L1TP_016035_20000127_20161002_01_T1 2000-01-27 0.00
LE70150352000036EDC00 LE07_L1TP_015035_20000205_20161003_01_T1 2000-02-05 7.00
LE70150352000052EDC00 LE07_L1TP_015035_20000221_20161002_01_T1 2000-02-21 0.00
...
```

Any help is highly appreciated :)

**Comment by yannforget** [comment]
Hello,

Thanks for your work on GRASS GIS and for the bug report!

That is because landsatxplore expects a bbox formatted as `(lat_min, lon_min, lat_max, lon_max)`. I'm gonna label the issue as a bug because it should not be the case..

**Comment by veroandreo** [comment]
Hello Yann, 

Thanks for your answer. I propose then to fix the documentation in landsatxplore, since X refers to longitude and Y to latitude and not as [here](https://github.com/yannforget/landsatxplore/#searching). Hence, the docs for bbox parameter should be (ymin, xmin, ymax, xmax).

**Comment by veroandreo** [comment]
I can confirm now that changing the order to (ymin, xmin, ymax, xmax) which is the equivalent of (lat_min, lon_min, lat_max, lon_max) fixes my problem. It's only documentation that needs to be updated accordingly. Confusing X with latitutde and Y with longitude is a very common problem :)
Thanks again!

**Comment by veroandreo** [comment]
This was fixed in later versions; I close
