### ISSUE TITLE
Collection 2 support?

### ISSUE THREAD

**Issue by jfprieur** [yannforget/landsatxplore#29]
Hello, I am sorry if I missed this elsewhere but are there any plans to support Collection 2 data? I just found this module and it would be highly useful in a pipeline I am created but we are using Collection 2 imagery.

Thank you!

**Comment by yannforget** [comment]
Hello,

Yes, I'm working on it for the next major version :)

**Comment by yannforget** [comment]
I added initial support for Collection 2 data in v0.12.0
