### ISSUE TITLE
Download skip / continue

### ISSUE THREAD

**Issue by alexVyth** [yannforget/landsatxplore#39]
Hello, great job on your APIs, congrats!

I think that the download method does not support skipping, if the file already exists and is correct.
Another interesting feature would be the continuation of incomplete downloads, in case of errors etc.

What are your thoughts? I could help if you are interested in these features.

**Comment by yannforget** [comment]
Hi and thanks for the feedback!

I agree with you. When I first started to work on the library, the servers did not support partial requests (no `Accept-Ranges` header) and did not provide hash values. Maybe this is possible now or there is another way to implement it ?

**Comment by alexVyth** [comment]
I guess we can't access any hash value. Looking at [https://m2m.cr.usgs.gov/api/docs/datatypes/](https://m2m.cr.usgs.gov/api/docs/datatypes) there is no mention about it.

So about skipping the download, checking the filesize on filesystem versus the filesize reported on metadata could be considered a safe solution?

I will investigate further about the download continuation.

**Comment by yannforget** [comment]
I would not trust the file size reported in the metadata. However the server provides a `content-length` HTTP header -- and we already get remote file size in `earthexplorer._download()` to initialize the progress bar

**Comment by alexVyth** [comment]
I think `Range` header is supported so if you agree I can make a pr with skipping download if local file size is the same as `Content-Length` header and download resume with header `Range={local_file_size}-` if the file exists but it's smaller than `Content-Length`.

**Comment by yannforget** [comment]
Good news! Of course I agree. Thanks :relaxed:

**Comment by alexVyth** [comment]
Do you know if the value of key `display_id` always matches the filename + some extension? (eg. <display_id>.tar.gz) 

I have some trouble implementing these features because I think that the filename is unknown until the `GET` request, which needs to be modified according to the filename. :flushed:
