### ISSUE TITLE
Error: "KeyError: 'content-disposition'"

### ISSUE THREAD

**Issue by Fenrihr** [yannforget/landsatxplore#4]
I'm trying to download several scenes with the following python script::
```python
from landsatxplore.earthexplorer import EarthExplorer

ee = EarthExplorer(LX_USERNAME, LX_PASSWORD)
i = 1
with open(FILE_SCENES, 'r') as input_data:
    for scene in input_data:
        print "[%s] -> %s" % (i, scene)
        ee.download(
            scene_id=str(scene), 
            output_dir='/home/usuario/descargas'
        )
        time.sleep(30*60) # Delay for 30 minute (1800 seconds).
ee.logout()
```

However, I keep receiving this error:
```python
Traceback (most recent call last):
  File "./script_descarga.py", line 34, in <module>
    output_dir=str(OUTPUT_DIR.absolute())
  File "/home/usuario/.local/lib/python2.7/site-packages/landsatxplore/earthexplorer.py", line 97, in download
    self._download(url, output_dir, file_size=SIZES[dataset])
  File "/home/usuario/.local/lib/python2.7/site-packages/landsatxplore/earthexplorer.py", line 82, in _download
    local_filename = r.headers['Content-Disposition'].split(
  File "/home/usuario/.local/lib/python2.7/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
```

It's like USGS is blocking the download, however, if I execute the request from the command line, `landsatxplore` works. Any suggestions?...

**Comment by yannforget** [comment]
Hi,

`ee.download()` was expecting the old scene identifier instead of the new product identifier. Do you have an example of the IDs you requested?

I just added an automatic conversion from `product_id` to `scene_id` to solve the issue. Can you try with the new version?

**Comment by Fenrihr** [comment]
Here some examples of the scenes: `LO82250822013096LGN02 LC82260822013117LGN02 LC82260822013181LGN01 LC82260822013197LGN01 LC82260822013229LGN01 LC82260822013245LGN01  LC82260822013309LGN01` . The file has a total of 75 scenes like these, one per line (obviously)

**Comment by Fenrihr** [comment]
Problem SOLVED!!!

One need to clean up the readed line of any `\n` or `\n\r` .... ups!!!
