### ISSUE TITLE
Limit to 20 images

### ISSUE THREAD

**Issue by Digdgeo** [yannforget/landsatxplore#6]
Hi,

Any kind of search that I do, only throws 20 images like maximun. So, if for instance, I try to look all the Landsat_TM_C1 collection, only get the first 20 from the beginning.

Is there anyway to skip this limitation?

Thank you so much

**Comment by yannforget** [comment]
Hi,

Yes, 20 is the default limit. Did you try `landsatxplore search --limit 100` to override it? Not sure if you will be able to fetch the whole collection though. Maybe it would be easier to just download the catalogue index from Google: https://storage.googleapis.com/gcp-public-data-landsat/index.csv.gz

**Comment by Digdgeo** [comment]
Thank Yann, 

--limit 100 it works, even 200 (not try more). But how could I insert this limit parameter in my python script?

This is what I am trying:

```

> scenes_etm = api.search(
>     dataset='LANDSAT_ETM_C1',
>     latitude=37.01,
>     longitude=-5.93,
>     start_date=year,
>     end_date=today,
>     max_cloud_cover=100,
>     limit=100)

```
But it's not working due that limit is not a valid parameter. 

Thanks again

Pd. By the way, I saw that I can include the start date in a loop, so I can go in a loop, every 6 month for example, and that way I can have the whole period (at least in the search, don't know in the download. I guess it will work too, because my download is also in a loop)

**Comment by yannforget** [comment]
Yes, my bad, the parameter name is different in the API. Try `max_results=100` instead of `limit=100`.

**Comment by Digdgeo** [comment]
Thanks so much, Yann. Now is working within my python script. And it seems that there's no problem to get the whole collection :)
