### ISSUE TITLE
Problem with Download

### ISSUE THREAD

**Issue by EveryoneInOne** [yannforget/landsatxplore#8]
Hi, 
I have problem with open_dir with your script , cause i have some errors with it. Can u help me?
I want use this script to download landsat images by python2.7 .
this is my code: 
import landsatxplore.api
from landsatxplore.earthexplorer import EarthExplorer

ee = EarthExplorer("*******, "********")
ee.download(scene_id='LT51960471995178MPS00', output_dir= 'I:\mmine\FILE\SCenes')

ee.logout()

and i have this erros:
Traceback (most recent call last):
  File "C:/Users/Przemo/Desktop/US2.py", line 6, in <module>
    ee.download(scene_id='LT51960471995178MPS00', output_dir= 'I:\mmine\FILE\SCenes')
  File "C:\Python27\ArcGIS10.6\lib\site-packages\landsatxplore\earthexplorer.py", line 96, in download
    filename = self._download(url, output_dir)
  File "C:\Python27\ArcGIS10.6\lib\site-packages\landsatxplore\earthexplorer.py", line 76, in _download
    with self.session.get(url, stream=True, allow_redirects=True) as r:
AttributeError: __exit__

**Comment by yannforget** [comment]
Hi,
how did you install the package? It is only available for Python 3.4+

**Comment by EveryoneInOne** [comment]
i install the package by pip  from https://pypi.org/project/landsatxplore/

**Comment by EveryoneInOne** [comment]
can u help me with that problem because i have to use the 2.7 version of python it was connected with the gis program like ArcGIS

**Comment by EveryoneInOne** [comment]
Because when i used the first part of script to show the scenes in accordance with the requirements it works and it show the scenes.
Script:
import arcpy
import os
from arcpy import env  
import landsatxplore.api
from landsatxplore.earthexplorer import EarthExplorer
arcpy.env.overwriteOutput = True

api = landsatxplore.api.API("*******", "*******")
scenes = api.search(
    dataset='LANDSAT_ETM_C1',
    latitude=19.53,
    longitude=-1.53,
    start_date='2016-01-01',
    end_date='2018-01-01',
    max_cloud_cover=10)

print('{} scenes found.'.format(len(scenes)))

for scene in scenes:
    print(scene['acquisitionDate']) 
OUTPUT:
20 scenes found.
2016-02-05
2016-02-05
2016-03-24
2016-04-09
2016-04-25
2016-04-25
2016-05-11
2016-05-11
2016-05-27
2016-05-27
2016-06-12
2016-06-12
2016-06-28
2016-06-28
2016-07-14
2016-07-14
2016-07-30
2016-08-15
2016-08-15
2016-10-18
and then second part doesnt work

**Comment by EveryoneInOne** [comment]
> 
> 
> Hi,
> how did you install the package? It is only available for Python 3.4+

?

**Comment by EveryoneInOne** [comment]
Hi,
i installed your package by pip and it works

Because when i used the first part of script to show the scenes in
accordance with the requirements it works and it show the scenes.
Script:
import arcpy
import os
from arcpy import env
import landsatxplore.api
from landsatxplore.earthexplorer import EarthExplorer
arcpy.env.overwriteOutput = True

api = landsatxplore.api.API("********", "*********")
scenes = api.search(
dataset='LANDSAT_ETM_C1',
latitude=19.53,
longitude=-1.53,
start_date='2016-01-01',
end_date='2018-01-01',
max_cloud_cover=10)

print('{} scenes found.'.format(len(scenes)))

for scene in scenes:
print(scene['acquisitionDate'])
OUTPUT:
20 scenes found.
2016-02-05
2016-02-05
2016-03-24
2016-04-09
2016-04-25
2016-04-25
2016-05-11
2016-05-11
2016-05-27
2016-05-27
2016-06-12
2016-06-12
2016-06-28
2016-06-28
2016-07-14
2016-07-14
2016-07-30
2016-08-15
2016-08-15
2016-10-18
and then second part doesnt work, when i try download one from that list i
cant

Greetings i waiting for your help

wt., 22 paź 2019 o 11:10 Yann Forget <notifications@github.com> napisał(a):

**Comment by yannforget** [comment]
Maybe try with forward slashes ? (`output_dir='I:/mmine/FILE/SCenes'`)

**Comment by EveryoneInOne** [comment]
i know but it still give eros
CODE:
import arcpy
import landsatxplore.api
from landsatxplore.earthexplorer import EarthExplorer

EE = EarthExplorer("*****", "*******")

EE.download(scene_id='LT51960471995178MPS00', output_dir=
'I:\mmine\FILE\SCenes')

EE.logout()
errors:
Runtime error
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File
"C:\Python27\ArcGIS10.6\lib\site-packages\landsatxplore\earthexplorer.py",
line 96, in download
    filename = self._download(url, output_dir)
  File
"C:\Python27\ArcGIS10.6\lib\site-packages\landsatxplore\earthexplorer.py",
line 76, in _download
    with self.session.get(url, stream=True, allow_redirects=True) as r:
AttributeError: __exit__
sorry for this problem but i neeed to fix it

czw., 24 paź 2019 o 11:57 Yann Forget <notifications@github.com> napisał(a):

**Comment by EveryoneInOne** [comment]
hi my now code:
import arcpy
import landsatxplore.api
from landsatxplore.earthexplorer import EarthExplorer
import os
EE = EarthExplorer("******", "*******")

EE.download(scene_id='LT51960471995178MPS00', output_dir=
'C:/Users/Przemo/landsat/LT51960471995178MPS00.tif')

EE.logout()


and the same errors, have u get any idea ?:
Traceback (most recent call last):
  File "C:\Users\Przemo\Desktop\dwd (1)\PYTHON_CODE\US2.py", line 7, in
<module>
    EE.download(scene_id='LT51960471995178MPS00', output_dir=
'C:/Users/Przemo/landsat/LT51960471995178MPS00.tif')
  File
"C:\Python27\ArcGIS10.6\lib\site-packages\landsatxplore\earthexplorer.py",
line 96, in download
    filename = self._download(url, output_dir)
  File
"C:\Python27\ArcGIS10.6\lib\site-packages\landsatxplore\earthexplorer.py",
line 76, in _download
    with self.session.get(url, stream=True, allow_redirects=True) as r:
AttributeError: __exit__
>>>


czw., 24 paź 2019 o 15:42 przemek kobialka <jestemtapmadl@gmail.com>
napisał(a):
