### ISSUE TITLE
Error when downloading: None of the archived ids succeeded! Update necessary!

### ISSUE THREAD

**Issue by BastosCaio** [yannforget/landsatxplore#99]
![error_using_Landsat_EarthExplorer](https://user-images.githubusercontent.com/32175834/236018523-15ae4261-edd9-465c-af1b-78fbfe8ba79e.PNG)

Hello,

I am trying to download a Landsat image using the code above, made from the examples given in the package documentation. The package doesn't seem to be able to download the image from the ID that was obtained using api.search function. 

The error that I'm getting is: "None of the archived ids succeeded! Update necessary!"

Does anybody know what could be wrong here?

**Comment by thomasoxe** [comment]
I get the same problem when trying to download newer Landsat-8 and -9 data

**Comment by hiyamdebary** [comment]
> I get the same problem when trying to download newer Landsat-8 and -9 data



> ![error_using_Landsat_EarthExplorer](https://user-images.githubusercontent.com/32175834/236018523-15ae4261-edd9-465c-af1b-78fbfe8ba79e.PNG)
> 
> Hello,
> 
> I am trying to download a Landsat image using the code above, made from the examples given in the package documentation. The package doesn't seem to be able to download the image from the ID that was obtained using api.search function.
> 
> The error that I'm getting is: "None of the archived ids succeeded! Update necessary!"
> 
> Does anybody know what could be wrong here?

Hello,
I have fixed this issue, see the commit https://github.com/yannforget/landsatxplore/compare/master...hiyamdebary:landsatxplore:master

**Comment by neteler** [comment]
> I have fixed this issue, see the commit [master...hiyamdebary:landsatxplore:master](https://github.com/yannforget/landsatxplore/compare/master...hiyamdebary:landsatxplore:master)

I have just merged your PR #106.
Please close this issue if it solved the problem, thanks.

**Comment by thomasoxe** [comment]
This worked for me, thanks:)

**Comment by thomasoxe** [comment]
Will you add this change to release?

**Comment by neteler** [comment]
> Will you add this change to release?

Unfortunately, while having meanwhile "merge" rights here I don't know how the pypi release procedure works.
Can @valpamp or @yannforget please help?
